version: "3"
services:
  neo4j:
    image: neo4j:4.1
    ports:
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/root
    volumes:
      - ./infra/container/data:/data:rw
   
  webapp:
    build: ./frontend
    ports:
      - "8000:8000"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: root
    depends_on:
      - neo4j
    restart: always