version: "3"
services:
  scraper:
    build: .
    environment:
      NEO4J_URI: bolt://localhost:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: root
      DEPTH_INTERACTIONS: 10
      FIRST_WORD: amor
    network_mode: "host"
